# Site settings
title: Staff AI Engineer
description: >
  Experienced Staff AI Engineer with over 6 years in AI, Machine Learning, and Deep Learning. Proven track record in
  leading cutting-edge projects in generative AI, NLP, and system optimization, improving performance by up to 40%. 
  Expertise in deploying AI solutions that drive operational efficiency, predictive accuracy, and customer engagement.
  Proficient in Python, C++, TensorFlow, and MLOps, with experience in managing large-scale projects and mentoring teams.
  Focused on leveraging AI technologies to solve complex business challenges and innovate industry solutions.

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Ankit Sharma"
title: Staff AI Engineer

# used for the contact button in _layouts/resume.html
resume_contact_email:           "ankitsharma224589@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
#resume_contact_telephone:       "+1(647) 860-3461"
resume_contact_address:         "Toronto, Canada"

resume_header_contact_info:     "Toronto, Canada • ankitsharma224589@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>Experienced Staff AI Engineer with over 6 years in AI, Machine Learning, and Deep Learning. Proven track record in
  leading cutting-edge projects in generative AI, NLP, and system optimization, improving performance by up to 40%. 
  Expertise in deploying AI solutions that drive operational efficiency, predictive accuracy, and customer engagement.
  Proficient in Python, C++, TensorFlow, and MLOps, with experience in managing large-scale projects and mentoring teams.
  Focused on leveraging AI technologies to solve complex business challenges and innovate industry solutions.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/ankitsharma224589"
  resume_linkedin_url:          "https://www.linkedin.com/in/ankitsharmatech"
  resume_website_url:           "https://ankitsharma.github.io"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
